version: '3.4'

services:
  dashboard:
    image: dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network  # Connect dashboard to app-network
    environment:
      DATABASE_HOST: mysql_container
      REDIS_HOST: redis_container

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network  # Connect MySQL to app-network

  redis:
    image: redis:alpine
    container_name: redis_container
    networks:
      - app-network  # Connect Redis to app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
